#!/bin/bash
cd "$(dirname $0)/guess_atm_in_idle_city_game_cache"
nNN="$1"
printControll="$2"
nNN6=35
nNN4=25

startUp () {
	numFound=0
	usedNumberNum=0
	unset usedNumber
	unset numberHasGot
	for (( r=1; r<=$nNN; r=r+1 ));do
	for (( i=1; i<=$nNN; i=i+1 ));do
	       col0[$i$r]="_"
	done
	done

	for (( i=1; i<=$nNN; i=i+1 ));do
	        colX[$i]="_"
	done
}

reached_critcal_level () {
  termux-notification --sound -t "Reached critical level"
  printf "Reached critical level\n"
  exit
}

startGame () {
  local critcal_level=1
  while true;do
    local ERROR=$(./start-new-game.co "$nNN")
    if [ "$ERROR" ];then
      if [ "$ERROR" == "ERROR" ];then
        sleep 8
      fi
      sleep 2
    else
      sleep 2
      break
    fi
    if [ $critcal_level -ge 5 ];then
      reached_critcal_level start
    fi
    critcal_level=$(( $critcal_level + 1 ))
  done
  tIME_star_main=$(date +%s)
}

storeUsedNumbers () {
  for (( k=1; k<=$nNN; k=k+1 ));do
    if [ "${usedNumber[$k]}" == "$1" ];then
      return
    fi
  done
  for (( k=1; k<=$nNN; k=k+1 ));do
    if [ -z "${usedNumber[$k]}" ];then
      usedNumber[$k]="$1"
      usedNumberNum=$(( "$usedNumberNum" + 1 ))
      break
    fi
  done
}

assignResultToArray () {
  for (( i=1; i<=$nNN; i=i+1 ));do
    res[$i]=$(echo $guessRes|cut -b$i )
  done
}

assignGotNumbersToArray () {
  local holdNum
  for (( i=1; i<=$nNN; i=i+1 ));do
  if [ "${res[$i]}" = "X" ];then
    if [ "${colX[$i]}" != "${num[$i]}" ];then
      numFound=$(($numFound + 1))
      holdNum=${num[$i]}
      colX[$i]=$holdNum
      numberHasGot[$holdNum]=$(( "${numberHasGot[$holdNum]}" + 1 ))
      storeUsedNumbers "${num[$i]}"
    fi
  fi
  done
}

assignExistNumbersToArray () {
  for (( i=1; i<=$nNN; i=i+1 ));do
    if [ "${res[$i]}" = "0" ];then
    	for (( r=1; r<=$nNN; r=r+1 ));do
    		if [ "${col0[$i$r]}" = "_" ];then
    			col0[$i$r]="${num[$i]}"
    			storeUsedNumbers "${num[$i]}"
    			break
    		fi
    	done
    fi
  done
}

getResult () {
  local critcal_level=1
  printf "| $clipGuess "
    unset guessRes
    gametrial=$(( "$gametrial" - 1 ))
  while true;do
    if [ $critcal_level -ge 3 ];then
      reached_critcal_level result
    fi
    echo -n "-> "
    guessRes=$(./send-to-bot.co $clipGuess)  
    if [ "$guessRes" ];then
      if [ "$guessRes" == "ERROR" ];then
        sleep 3
      else
        break
      fi
    fi
    critcal_level=$(( $critcal_level + 1 ))
  done
  if [ "$gametrial" == "0" ];then
    gametrialEnded=1
  fi
  printf "$guessRes | $gametrial\n"
}

assigner () {
  getResult
  if [ "$gametrialEnded" == "1" ];then
    return
  fi
  assignResultToArray
  assignGotNumbersToArray
  assignExistNumbersToArray
  #fullPrint
}

fullPrint () {
  clear
  case "$printControll" in 
    "p" | "f" ) #  printUnderLineBridge
    printRowOfX
    printUnderLineBridge
    ;;
  esac

  if [ "$printControll" == "f" ];then
    printRowANDColumnOf0
    printUnderLineBridge
  fi
    printf "$usedNumberNum:${usedNumber[*]}\n"
}

printRowOfX () {
  printf "| "
  for (( i=1; i<=$nNN; i=i+1 ));do
    if [ $i = 4 ];then
            printf "| "
    fi
    if [ $i = 1 ];then
            printf "\033[1;32m${colX[$i]} "
    elif [ $i = 2 ];then
            printf "\033[1;33m${colX[$i]} "
    elif [ $i = 3 ];then
            printf "\033[1;31m${colX[$i]}\033[0m "
    elif [ $i = 4 ];then
            printf "\033[1;32m${colX[$i]}\033[0m "
    elif [ $i = 5 ];then
            printf "\033[1;35m${colX[$i]} "
    elif [ $i = 6 ];then
            printf "\033[1;37m${colX[$i]}\033[0m "
    fi
  done
  printf "|\n"
}

printRowANDColumnOf0 () {
  for (( r=1; r<=$nNN; r=r+1 ));do
    printf "| "
    for (( i=1; i<=$nNN; i=i+1 ));do
      if [ $i = 4 ];then
        printf "| "
      fi
      if [ $i = 1 ];then
        printf "\033[1;32m${col0[$i$r]} "
      elif [ $i = 2 ];then
        printf "\033[1;33m${col0[$i$r]} "
      elif [ $i = 3 ];then
        printf "\033[1;31m${col0[$i$r]}\033[0m "
      elif [ $i = 4 ];then
        printf "\033[1;32m${col0[$i$r]}\033[0m "
      elif [ $i = 5 ];then
        printf "\033[1;35m${col0[$i$r]} "
      elif [ $i = 6 ];then
        printf "\033[1;37m${col0[$i$r]}\033[0m "
      fi
    done
      printf "|\n"
  done
}

printUnderLineBridge () {
  if [ "$nNN" == "6" ];then
    printf "|-------|-------|\n"
  elif [ "$nNN" == "4" ];then
    printf "|-------|---|\n"
  fi
}

checkFromColumn () {
  if [ "${colX[$1]}" == "_" ];then
    for (( c=1; c<=$nNN; c=c+1 ));do
  	  if [ "${col0[$1$c]}" == "$2" ];then
  	    return 1
      fi
    done
  else
    return 2
  fi
  return 0
}

rearrangeNumbers () {
  local iii
  local regCol
  local mainNum="$1"
  findAvailableNumberForColumn () {
    local mainNum2="$1"
    local numberCanIn
    local numberCanInCol
    local numtmp
    for (( hh=1; hh<=$usedNumberNum; hh=hh+1 ));do
      checkFromColumn $1 ${usedNumber[$hh]}
      if [ "$?" == "0" ];then
        numberCanIn+=(${usedNumber[$hh]})
      fi
    done
  
    for ii in ${numberCanIn[@]};do
      for (( co=1; co<=$nNN; co=co+1 ));do
        if [ ! "${regCol[$co]}" ];then  
          if [ "${num[$co]}" == "$ii" ];then
            if [ "${colX[$co]}" != "$ii" ];then
              numberCanInCol+=($co)
              regCol[$co]=1
              numtmp[$co]="$ii"
            fi
          fi
        fi
      done
    done
  
    for ii in ${numberCanInCol[@]};do
      checkFromColumn $ii $mainNum
      if [ "$?" == "0" ];then
        num[$mainNum2]=${num[$ii]}
        unset num[$ii]
        return 8
      fi
    done
    
    for iii in ${numberCanInCol[@]};do
      echo calling checkChange again
      findAvailableNumberForColumn $iii
      if [ "$?" == "8" ];then
        num[$mainNum2]=${numtmp[$iii]}
        return 8
      fi
    done
  }
  for (( h=1; h<=$nNN; h=h+1 ));do
    if  [ -z "${num[$h]}" ];then
      findAvailableNumberForColumn $h
      if [ "$?" == 8 ];then
        break
      fi
    fi
  done
}

fillRemainingNumbers () {
  unset num clipGuess
  num=0
  local mm
  local current
  local foundInClo
  local guessedCol
  local guessedNum=0
  
  if [ "$nNN" == "4" ];then
    local numbersRemaining=(0 8 9)
  elif [ "$nNN" == "6" ];then
    local numbersRemaining=(0 6 7 8 9)
  elif [ "$nNN" == "8" ];then
    local numbersRemaining=(0 8 9)
  fi
  
  for (( i=1; i<=$usedNumberNum; i=i+1 ));do
    current="${usedNumber[$i]}"
    	for (( r=1; r<=$nNN; r=r+1 ));do
        checkFromColumn $r $current
      	foundInClo=$?
      	if [ "$foundInClo" == 0 ];then
        	if [ -z "${guessedCol[$r]}" ];then
        	  guessedCol[$r]=$current
        	  guessedNum=$(( "$guessedNum" + 1 ))
        	fi
        	if [ "$guessedNum" == 2 ];then
        	  mm=1
        	  for (( c=1; c<=$nNN; c=c+1 ));do
        	    if [ -z "${guessedCol[$c]}" ];then
        	      clipGuess+="${numbersRemaining[$mm]}"
        	      num+=(${numbersRemaining[$mm]})
        	      mm=$(( $mm + 1 ))
        	    else
        	      clipGuess+="${guessedCol[$c]}"
        	      num+=(${guessedCol[$c]})
        	    fi
        	  done
        	  return
        	fi
      	fi
      done
  done
}

numberGenerater () {
  startUp
  if [ "$nNN" == "4" ];then
    clipGuess=0123
    num=(0 0 1 2 3)
  elif [ "$nNN" == "6" ];then
    clipGuess=012345
    num=(0 0 1 2 3 4 5)
  fi
  
  assigner
  if [ "$gametrialEnded" == "1" ];then
    return
  fi
  
  if [ "$usedNumberNum" == "$nNN" ];then
    return
  fi
  
  if [ "$nNN" == "4" ];then
    clipGuess=4567
    num=(0 4 5 6 7)
    assigner
    if [ "$gametrialEnded" == "1" ];then
      return
    fi
    if [ "$usedNumberNum" == "$nNN" ];then
      return
    fi
  fi
  
  if [ "$usedNumberNum" == "0" ];then
    if [ "$nNN" == "4" ];then
      clipGuess=8899
      num=(0 8 8 9 9)
      assigner
      return
    elif [ "$nNN" == "6" ];then
      clipGuess=666789
      num=(0 6 6 6 7 8 9)
      assigner
      return
    fi
  fi
    fillRemainingNumbers
    assigner
    return
}

guessNextNumber () {
  unset num clipGuess
  num=0
  local foundInClo
  local current
  local guessedNum=0
  local addedCheck
  for (( i=1; i<=$nNN; i=i+1 ));do
    if [ "${colX[$i]}" != "_" ];then
      num[$i]="${colX[$i]}"
      guessedNum=$(( "$guessedNum" + 1 ))
    fi
  done

  for (( i=1; i<=$usedNumberNum; i=i+1 ));do
    current="${usedNumber[$i]}"
    #echo "\"${numberHasGot[$current]}\" $current $i"
    #sleep 2
    
    if [ ! "${numberHasGot[$current]}" ];then
      while true;do
        addedCheck=0
      	for (( r=1; r<=$nNN; r=r+1 ));do
          if [ -z "${num[$r]}" ];then
            checkFromColumn $r $current
        	  foundInClo=$?
        	  if [ "$foundInClo" == "0" ];then
            	  num[$r]=$current
            	  guessedNum=$(( "$guessedNum" + 1 ))
                addedCheck=1
            	  break
        	  fi
        	fi
        done
        if [ "$addedCheck" == "1" ];then
        #echo "finished \"$current\" \"$i\""
        #echo ${num[@]}
        #sleep 2
          break
        elif [ "$addedCheck" == "0" ];then
          #echo "\"$i\" \"${num[5]}\" and \"${num[6]}\""
          rearrangeNumbers $current
          #echo "\"$i\" \"${num[5]}\" and \"${num[6]}\""
          #sleep 8888
        fi
      done
    fi
  done
  
  if [ "$guessedNum" == "$nNN" ];then
    for (( g=1; g<=$nNN; g=g+1 ));do
      clipGuess+="${num[$g]}"
    done
  else
    while true;do
      for (( i=1; i<=$usedNumberNum; i=i+1 ));do
        current="${usedNumber[$i]}"
      	for (( r=1; r<=$nNN; r=r+1 ));do
          if [ -z "${num[$r]}" ];then
            checkFromColumn $r $current
        	  foundInClo=$?
        	  if [ "$foundInClo" == "0" ];then
            	  num[$r]=$current
            	  guessedNum=$(( "$guessedNum" + 1 ))
            	  break
        	  fi
        	fi
        done
      done
      if [ "$guessedNum" == "$nNN" ];then
        for (( g=1; g<=$nNN; g=g+1 ));do
          clipGuess+="${num[$g]}"
        done
        break
      fi
    done
  fi
}

guesser () {
  while true;do
    guessNextNumber
    assigner
    if [ "$gametrialEnded" == "1" ];then
      return
    fi
    if [ "$numFound" = "$nNN" ];then
      break
    fi
  done
}

changeTimeFormat () {
  local size="$@"
  local hr="0"
  local min="0"
  local sec="0"
  until [ $size == "0" ]; do
    if [[ "$size" -ge "3600" ]];then
      printf "$(($size / 3600)) hr "
      size=$(($size%3600))
    elif [[ "$size" -ge "60" && "$size" -lt "3600" ]]; then
      printf "$(($size / 60)) min "
      size=$(($size%60))
    else 
      printf "$size sec "
      break
    fi
  done
    if [[ "$@" == 0 ]];then
      printf "0 sec "
    fi
}

main () {
  if [[ "$nNN" == 6 || "$nNN" == 4 ]];then
    startGame
  else
    nNN=6
    printf "I can only guess 
4 or 6(default) pins\n"
    startGame
  fi
  if [ "$nNN" == "4" ];then
    gametrial=$nNN4
  elif [ "$nNN" == "6" ];then
    gametrial=$nNN6
  fi
  gametrialEnded=0
  game_played=0
  hacked_game=0
  game_started=$(date +%s)
  printUnderLineBridge
  while true;do
  tIME_star=$(date +%s)
    numberGenerater
    if [ "$gametrialEnded" == "1" ];then
      gametrialEnded=0
      tIME_end_main=$(date +%s)
      game_played=$(($game_played + 1))
      clear
      printUnderLineBridge
      printf "| Done in $( changeTimeFormat $(expr $tIME_end_main - $tIME_star_main) )\n"
      printf "| $game_played game played\n"
      printf "| $hacked_game atm Hacked\n"
      printf "| Time $( changeTimeFormat $(expr $(date +%s) - $game_started) )\n"
      printUnderLineBridge
      if [ "$nNN" == "4" ];then
        gametrial=$nNN4
      elif [ "$nNN" == "6" ];then
        gametrial=$nNN6
      fi
      startGame
      continue
    else
      guesser
      if [ "$gametrialEnded" == "1" ];then
        gametrialEnded=0
        tIME_end_main=$(date +%s)
        game_played=$(($game_played + 1))
        clear
        printUnderLineBridge
        printf "| Done in $( changeTimeFormat $(expr $tIME_end_main - $tIME_star_main) )\n"
        printf "| $game_played game played\n"
        printf "| $hacked_game atm Hacked\n"
        printf "| Time $( changeTimeFormat $(expr $(date +%s) - $game_started) )\n"
        printUnderLineBridge
        if [ "$nNN" == "4" ];then
          gametrial=$nNN4
        elif [ "$nNN" == "6" ];then
          gametrial=$nNN6
        fi
        startGame
        continue
      fi
    fi
    tIME_end=$(date +%s)
    printUnderLineBridge
    printf "| Hacked in $( changeTimeFormat $(expr $tIME_end - $tIME_star) )\n"
    printUnderLineBridge
    hacked_game=$(($hacked_game + 1))
  done
}

./get-result.co
clear
main
